### PR TITLE
No-op update to refresh build

### PR DESCRIPTION
**Pull request by gparvin**
Go changes did not clear build.  Trying one more build.

Refs:
 - https://github.com/stolostron/backlog/issues/23977

Signed-off-by: Gus Parvin <gparvin@redhat.com>

### CODE REVIEW

**Comment by gparvin** [comment]
@dhaiducek The go changes were merged yesterday but this is still failing.  Trying another build but I don't see failures in ci jobs -- just the continued vulnerabilities in quay that look like the image wasn't updated...

**Comment by dhaiducek** [comment]
Looking into it, but this PR should go against `main` if there is an issue. PRs directly to `release-2.6` will break fast-fowarding.

**Comment by dhaiducek** [comment]
Actually, that's 100% the issue. Your PR for Go 1.18 was against `release-2.6`, but promotions to `2.6` internally in Prow happen on `main` and then are published when they hit `release-2.6`.

**Comment by gparvin** [comment]
Don't need this pr then...

**Pull request closed without merging**
